// 完整资料沿用原页面数据；仅调整阅读层级，不截断或删除原始说明。
(()=>{
const originalRender=render;
const dict={zh:{preview:'完整内容 · 图片视觉预览',expand:'展开全部详情',collapse:'收起全部详情',details:'完整介绍与资料',search:'搜索项目名称、用途或技术',all:'全部项目',shown:'当前显示',clear:'清空筛选',none:'没有匹配项目。清空搜索即可查看全部项目。',art:'生成概念视觉',snapshot:'星标与贡献数据沿用原站记录，非实时统计。',counts:(a,p,r)=>`4 项竞赛荣誉 · ${a} 项成果奖项 · ${p} 个个人项目 · ${r} 个贡献仓库`},en:{preview:'Complete portfolio · Visual preview',expand:'Expand all details',collapse:'Collapse all details',details:'Full description & resources',search:'Search projects, purpose or technology',all:'All projects',shown:'Showing',clear:'Clear filters',none:'No matching projects. Clear search to see all projects.',art:'Generated concept artwork',snapshot:'Stars and contribution data retain the original site snapshot; not live statistics.',counts:(a,p,r)=>`4 competition honors · ${a} awards · ${p} projects · ${r} contribution repositories`},ja:{preview:'全コンテンツ · ビジュアルプレビュー',expand:'詳細をすべて開く',collapse:'詳細をすべて閉じる',details:'紹介全文と資料',search:'プロジェクト・用途・技術を検索',all:'全プロジェクト',shown:'表示件数',clear:'検索を解除',none:'該当なし。検索を解除するとすべて表示されます。',art:'生成したコンセプト画像',snapshot:'スター数と貢献データは元サイトの記録で、リアルタイムの統計ではありません。',counts:(a,p,r)=>`コンペ受賞 4 件 · 受賞 ${a} 件 · プロジェクト ${p} 件 · 貢献リポジトリ ${r} 件`}};
function enhance(lang){const c=content[lang]||content.zh,t=dict[lang]||dict.zh;
 document.body.classList.add('complete-preview');
 let strip=document.querySelector('.preview-controls');if(!strip){strip=document.createElement('div');strip.className='preview-controls';document.querySelector('.portfolio-hero .section-inner').append(strip);}strip.innerHTML=`<div><span class="preview-label">${t.preview}</span><p>${t.counts(c.awardsList.length,c.projectsList.length,c.contributionRepos.length)}</p></div><button id="all-details">${t.expand}</button>`;
 for(const [id,key] of [['competitions','honors'],['awards','awards'],['communication','sharing'],['projects','projects']]){const header=document.querySelector(`#${id} .section-header`);header.classList.add('art-heading');let art=header.querySelector('.art-frame');if(!art){art=document.createElement('figure');art.className='art-frame';header.append(art);}art.innerHTML=`<img src="assets/generated/${key}-handdrawn-v2.png" alt="" loading="lazy"><figcaption>${t.art}</figcaption>`;art.onpointermove=e=>{if(e.pointerType!=='mouse'||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const r=art.getBoundingClientRect();art.style.transform=`perspective(1000px) rotateX(${-(e.clientY-r.top-r.height/2)/r.height*5}deg) rotateY(${(e.clientX-r.left-r.width/2)/r.width*6}deg)`;};art.onpointerleave=()=>art.style.transform='';}
 // 成果奖项所有标题和项目名直接可见，完整原文放入原位详情。
 document.querySelectorAll('.award-item').forEach((item,i)=>{const meta=item.querySelector('.award-meta');const d=document.createElement('details');d.className='full-detail';d.innerHTML=`<summary>${t.details}</summary>`;meta.before(d);d.append(meta);item.dataset.record=`awardsList:${i}`;});
 // 项目名称、简短用途与主要入口始终保留；原始图片、描述、标签、星标与链接移入详情。
 document.querySelectorAll('[data-render="projects"] .project-card').forEach((card,i)=>{const data=c.projectsList[i];card.classList.remove('tilt-card');card.removeAttribute('style');card.dataset.record=`projectsList:${i}`;card.dataset.search=JSON.stringify(data).toLowerCase();
 const body=card.querySelector('.project-body');const heading=body.querySelector('.project-top');const d=document.createElement('details');d.className='full-detail';d.innerHTML=`<summary>${t.details}</summary>`;const media=card.querySelector('.project-media');if(media)d.append(media);[...body.children].filter(el=>el!==heading).forEach(el=>d.append(el));
 const concise=document.createElement('p');concise.className='project-concise';concise.textContent=data.desc.split(/(?<=[。.!?])\s+/)[0];body.append(concise);
 const quick=document.createElement('a');quick.href=data.siteUrl||data.url;quick.target='_blank';quick.rel='noopener noreferrer';quick.className='quick-link';quick.textContent=(data.siteUrl?c.projects.site:c.projects.link)+' ↗';body.append(quick,d);
 const n=document.createElement('span');n.className='project-number';n.textContent=String(i+1).padStart(2,'0');heading.prepend(n);
 });
 let search=document.querySelector('.project-search');if(!search){search=document.createElement('div');search.className='project-search';document.querySelector('[data-render="projects"]').before(search);}const allTags=[...new Set(c.projectsList.flatMap(x=>x.tags))];search.innerHTML=`<label class="search-label"><span>${t.search}</span><input type="search" aria-label="${t.search}" placeholder="${t.search}"></label><select aria-label="${t.all}"><option value="">${t.all}</option>${allTags.map(tag=>`<option>${escapeHtml(tag)}</option>`).join('')}</select><button class="clear-search">${t.clear}</button><span class="search-count" aria-live="polite"></span><p class="empty-search" hidden>${t.none}</p>`;
 const filter=()=>{const q=search.querySelector('input').value.trim().toLowerCase(),tag=search.querySelector('select').value;let n=0;document.querySelectorAll('[data-render="projects"] .project-card').forEach((card,i)=>{card.hidden=!(card.dataset.search.includes(q)&&(!tag||c.projectsList[i].tags.includes(tag)));if(!card.hidden)n++;});search.querySelector('.search-count').textContent=`${t.shown} ${n} / ${c.projectsList.length}`;search.querySelector('.empty-search').hidden=n!==0;};search.querySelector('input').oninput=filter;search.querySelector('select').onchange=filter;search.querySelector('.clear-search').onclick=()=>{search.querySelector('input').value='';search.querySelector('select').value='';filter();};filter();
 let note=document.querySelector('.snapshot-note');if(!note){note=document.createElement('p');note.className='snapshot-note';document.querySelector('[data-render="projects"]').after(note);}note.textContent=t.snapshot;
 const btn=document.querySelector('#all-details');btn.onclick=()=>{const expand=![...document.querySelectorAll('#portfolio .full-detail')].every(d=>d.open);document.querySelectorAll('#portfolio .full-detail').forEach(d=>d.open=expand);btn.textContent=expand?t.collapse:t.expand;};
 document.querySelectorAll('#portfolio .full-detail').forEach(d=>d.addEventListener('toggle',()=>{btn.textContent=[...document.querySelectorAll('#portfolio .full-detail')].every(x=>x.open)?t.collapse:t.expand;}));
 window.completePreview={language:lang,awards:c.awardsList.length,projects:c.projectsList.length,contributions:c.contributionRepos.length,communication:c.communicationList.length,appointments:c.appointmentsList.length,skills:c.skillsList.length};
}
render=function(lang){originalRender(lang);enhance(lang);};
enhance(document.documentElement.lang.startsWith('zh')?'zh':document.documentElement.lang.startsWith('ja')?'ja':'en');
})();
