/* Shared Kaggle honors. Rankings and dates follow supplied certificates. */
const kaggleAwards = [
 {id:'ptcg',title:'The Pokémon Company — PTCG AI Battle Challenge Simulation',rank:253,teams:6807,top:'3.7',date:'2026-09-01',kind:'silver',org:'The Pokémon Company',url:'pokemon-tcg-ai-battle'},
 {id:'rna',title:'Stanford RNA 3D Folding',rank:55,teams:1516,top:'3.6',date:'2025-09-25',kind:'silver',org:'Stanford University',url:'stanford-rna-3d-folding'},
 {id:'cibmtr',title:'CIBMTR — Equity in post-HCT Survival Predictions',rank:83,teams:3325,top:'2.5',date:'2025-03-06',kind:'silver',org:'CIBMTR',url:'equity-post-HCT-survival-predictions'},
 {id:'cryo',title:'CZII — CryoET Object Identification',rank:51,teams:931,top:'5.5',date:'2025-02-06',kind:'bronze',org:'CZ Imaging Institute',url:'czii-cryo-et-object-identification'}
];
const kaggleCopy={
 zh:{subtitle:'在汇聚全球 3,300 万数据科学家、机器学习工程师与爱好者的平台上，参与真实问题的 AI 竞赛。',source:'平台规模来源：Kaggle 官方首页 · 2026-09 核对',summary:'3 枚银牌 · 1 枚铜牌',profile:'Kaggle 个人主页',latest:'最新荣誉 · 2026',silver:'银牌',bronze:'铜牌',rank:'名次 / 参赛队伍',cert:'查看证书',event:'赛事详情',close:'关闭证书',date:'获奖日期',org:'主办方',titles:['宝可梦卡牌 AI 对战挑战赛','RNA 三维结构预测','移植后生存预测公平性','冷冻电镜三维目标识别'],descs:['围绕宝可梦卡牌对战，探索 AI 智能体的策略规划与决策。','面向 RNA 分子的三维折叠结构预测，探索生命科学中的计算难题。','围绕造血干细胞移植后的生存预测，关注模型在不同人群中的公平性。','在冷冻电子断层扫描数据中识别蛋白质复合物，探索三维目标检测。']},
 en:{subtitle:'Competing on real-world AI challenges in a global community of 33 million data scientists, ML engineers and enthusiasts.',source:'Community size: Kaggle official homepage · checked Sep 2026',summary:'3 silver medals · 1 bronze medal',profile:'Kaggle profile',latest:'LATEST HONOR · 2026',silver:'Silver medal',bronze:'Bronze medal',rank:'Rank / competing teams',cert:'View certificate',event:'Competition',close:'Close certificate',date:'Awarded',org:'Organizer',titles:['Pokémon TCG AI Battle Challenge','RNA 3D structure prediction','Equity in post-HCT survival predictions','CryoET object identification'],descs:['Exploring strategic planning and decision-making with AI agents in Pokémon Trading Card Game battles.','Predicting RNA molecular 3D structures in a computational life-science challenge.','Exploring equitable survival predictions across populations after hematopoietic stem cell transplantation.','Identifying protein complexes in cryo-electron tomography through 3D object detection.']},
 ja:{subtitle:'世界 3,300 万人のデータサイエンティスト、機械学習エンジニア、愛好家が集う場で、実課題の AI コンペに挑戦。',source:'コミュニティ規模：Kaggle 公式サイト · 2026年9月確認',summary:'銀メダル 3 枚 · 銅メダル 1 枚',profile:'Kaggle プロフィール',latest:'最新の受賞 · 2026',silver:'銀メダル',bronze:'銅メダル',rank:'順位 / 参加チーム',cert:'証明書を見る',event:'コンペ詳細',close:'証明書を閉じる',date:'受賞日',org:'主催',titles:['ポケモンカード AI 対戦チャレンジ','RNA 三次元構造予測','移植後生存予測の公平性','CryoET 三次元物体検出'],descs:['ポケモンカード対戦における AI エージェントの戦略立案と意思決定を探究。','RNA 分子の三次元構造予測を通じて、生命科学の計算課題に挑戦。','造血幹細胞移植後の生存予測で、異なる集団間の公平性を探究。','クライオ電子線トモグラフィーで、タンパク質複合体の三次元検出に挑戦。']}
};
function renderKaggleHonors(lang){
 const c=kaggleCopy[lang]||kaggleCopy.en, root=document.querySelector('[data-render="competitions"]');
 root.classList.add('honors-grid');
 let intro=document.querySelector('.honors-intro');
 if(!intro){intro=document.createElement('div');intro.className='honors-intro';root.before(intro);}
 intro.innerHTML=`<p class="honors-subtitle">${c.subtitle}</p><a class="honors-source" href="https://www.kaggle.com/" target="_blank" rel="noopener noreferrer">${c.source} ↗</a><div class="honors-summary"><strong>${c.summary}</strong><a href="https://www.kaggle.com/lixinyin" target="_blank" rel="noopener noreferrer">${c.profile} ↗</a></div>`;
 root.innerHTML=kaggleAwards.map((a,i)=>`<article class="honor-card" style="--honor-delay:${i*80}ms"><div class="honor-medal ${a.kind}" aria-hidden="true"><div class="honor-medal-face"><span>${a.kind.toUpperCase()}</span><b>k</b><span>${a.date.slice(0,4)}</span></div></div><div class="honor-body"><p class="honor-eyebrow">${i===0?c.latest:c[a.kind]}</p><h3>${c.titles[i]}</h3><p class="honor-official">${a.title}</p><div class="honor-score"><div><strong>${a.rank}<small> / ${a.teams.toLocaleString('en-US')}</small></strong><span>${c.rank}</span></div><b>Top ${a.top}%</b></div><p class="honor-desc">${c.descs[i]}</p><p class="honor-meta">${c.org}：${a.org}<br>${c.date}：<time datetime="${a.date}">${a.date}</time> · ${c[a.kind]}</p><div class="honor-links"><a href="assets/kaggle-honors/${a.id}.jpg" data-certificate="${a.id}">${c.cert} ↗</a><a href="https://www.kaggle.com/competitions/${a.url}" target="_blank" rel="noopener noreferrer">${c.event} ↗</a></div></div></article>`).join('');
 let dialog=document.querySelector('#honor-certificate');
 if(!dialog){dialog=document.createElement('dialog');dialog.id='honor-certificate';document.body.append(dialog);dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});}
 dialog.innerHTML=`<form method="dialog"><button aria-label="${c.close}">${c.close} ×</button></form><img alt=""><a class="honor-original" target="_blank" rel="noopener noreferrer">${c.cert} ↗</a>`;
 root.querySelectorAll('[data-certificate]').forEach(link=>link.addEventListener('click',e=>{e.preventDefault();const a=kaggleAwards.find(x=>x.id===link.dataset.certificate);dialog.querySelector('img').src=link.href;dialog.querySelector('img').alt=`Lixin Yin — ${a.title} — ${c[a.kind]} — ${a.rank}/${a.teams}`;dialog.querySelector('.honor-original').href=link.href;dialog.showModal();}));
}
