import * as THREE from './vendor/three.module.js';

// 年代是事件节点而非等比例刻度；远古地貌为程序化示意。
const records = [
  ['4.54 Ga','火与尘埃，汇成地球','A world forged in fire','炎と塵から生まれた地球','太阳系中的物质在引力作用下聚集。碰撞、熔融与分层塑造了年轻地球，生命的舞台尚未准备好。','Gravity assembled our planet. Impacts and melting shaped a young world before life.','重力によって物質が集まり、衝突と溶融が若い地球を形づくりました。',0,'星球形成','Planet formation','惑星の形成'],
  ['4.4 Ga','第一片海洋','The first oceans','最初の海','地表逐渐冷却，液态水开始参与岩石与大气的循环。古老锆石为早期水环境提供线索，海洋形成的具体过程仍在研究中。','Cooling made liquid water possible. Ancient zircons preserve clues to early water, not a complete ocean map.','地表が冷え、液体の水が循環へ。古いジルコンが初期の水環境の手がかりを残しています。',1,'水的世界','A water world','水の世界'],
  ['3.5 Ga','微小生命，漫长开端','Small beginnings','小さな生命の始まり','微生物成为早期生命的重要成员。叠层石记录了古老微生物群落的活动，但生命究竟如何起源，仍是开放问题。','Stromatolites record ancient microbial communities. The precise origin of life remains an open question.','ストロマトライトに残る微生物群集の記録。生命の起源には未解決の問いが残っています。',1,'早期生命','Early life','初期の生命'],
  ['2.4 Ga','生命，改变天空','Life changes the sky','生命が空を変える','产氧光合作用逐渐改变地球化学环境。大气中氧气持续积累，为生命打开新的可能，也给厌氧生物带来压力。','Oxygen-producing photosynthesis transformed the environment, creating opportunities and challenges for life.','酸素を生み出す光合成が環境を変え、生命に新しい可能性と困難をもたらしました。',2,'大氧化事件','Great Oxidation','大酸化イベント'],
  ['1.8 Ga','细胞内部的新世界','A world within a cell','細胞の中の新世界','真核细胞拥有更复杂的内部结构。内共生是理解线粒体起源的重要框架，复杂生命的基础逐步形成。','Eukaryotic cells developed complex internal organization. Endosymbiosis helps explain the origin of mitochondria.','真核細胞の複雑な内部構造。細胞内共生はミトコンドリアの起源を理解する鍵です。',2,'复杂细胞','Complex cells','複雑な細胞'],
  ['650 Ma','冰封的星球','An icebound world','氷に覆われた世界','成冰纪的强烈冰期可能让冰延伸到低纬度。冰、海洋、大气与火山活动相互作用，生命仍在继续。','Cryogenian glaciations reached low latitudes. Ice, ocean, atmosphere and volcanism reshaped habitats.','クライオジェニアン紀には氷床が低緯度へ。氷・海・大気・火山が生息環境を変えました。',3,'雪球地球','Snowball Earth','スノーボールアース'],
  ['575 Ma','海底，出现新的身影','New lives on the seafloor','海底に現れた新しい姿','埃迪卡拉生物群留下大型多细胞生物的印迹。它们的身体形态与今天很不一样，许多亲缘关系仍有争议。','Ediacaran fossils reveal large multicellular organisms, many with unfamiliar bodies and debated relationships.','エディアカラ生物群の化石は大型多細胞生物を記録し、その系統には議論も残ります。',4,'多细胞生命','Multicellular life','多細胞の生命'],
  ['539 Ma','生命的形态，迅速展开','Life diversifies','生命のかたちが広がる','寒武纪期间，多类动物快速多样化。捕食、运动与硬质结构让海洋生态关系变得更复杂；这并非生命突然从无到有。','During the Cambrian, animal diversity expanded. Predation, movement and hard parts transformed marine ecosystems.','カンブリア紀には動物が多様化。捕食・運動・硬い殻が海洋生態系を変化させました。',4,'寒武纪辐射','Cambrian radiation','カンブリア紀の多様化'],
  ['430 Ma','生命走向陆地','Life reaches the land','生命が陸へ','植物与节肢动物等逐步拓展陆地环境。此后森林与陆地脊椎动物发展，土壤、碳循环和栖息地也随之改变。','Plants and arthropods expanded on land. Forests and terrestrial vertebrates later transformed soils and habitats.','植物や節足動物が陸地へ進出。その後、森林や陸上脊椎動物が生息環境を変えました。',5,'陆地生态','Life on land','陸上の生態系'],
  ['300 Ma','大陆相遇，盘古成形','Continents come together','大陸が集まる','板块运动让大陆汇聚成盘古大陆。海岸、气候和生物交流随之改变，陆地上的生命沿着新的路径扩散。','Plate motion assembled Pangaea, changing coasts, climates and connections between living populations.','プレート運動でパンゲアが形成され、海岸・気候・生物の移動経路が変化しました。',6,'盘古大陆','Pangaea','パンゲア'],
  ['252 Ma','危机之后，重新繁盛','After the great dying','大量絶滅のあとで','二叠纪末的大灭绝重创海洋与陆地生态系统。恢复耗时漫长，幸存谱系在改变后的环境中继续演化。','The end-Permian extinction devastated ecosystems. Surviving lineages evolved through a prolonged recovery.','ペルム紀末の大量絶滅が生態系を激変。生き残った系統は長い回復期を経ました。',7,'灭绝与恢复','Extinction & recovery','絶滅と回復'],
  ['150 Ma','大陆分离，生命分流','Worlds drift apart','離れていく大陸','盘古大陆逐渐分裂，新的海洋打开。恐龙活跃于陆地，早期鸟类和哺乳动物也在各自的生态空间中演化。','Pangaea fragmented and new oceans opened. Dinosaurs, early birds and mammals occupied changing habitats.','パンゲアが分裂し、新しい海洋が開きました。恐竜・初期の鳥類・哺乳類が進化を続けます。',8,'中生代世界','Mesozoic world','中生代の世界'],
  ['66 Ma','一次终结，无数开端','An ending. New beginnings.','終わりと新しい始まり','白垩纪末的撞击及其环境后果引发大灭绝，非鸟恐龙消失。幸存鸟类、哺乳动物等在新生代继续多样化。','An impact and its consequences drove the end-Cretaceous extinction. Surviving birds and mammals diversified.','白亜紀末の衝突と環境変動で大量絶滅が起き、生き残った鳥類や哺乳類が多様化しました。',9,'新生代的序幕','A Cenozoic beginning','新生代の始まり'],
  ['NOW','我们的地球，仍在演化','Our living planet','進化を続ける地球','海洋、大气、岩石与生命共同塑造着今天。智人约在 30 万年前出现，只占漫长地球历史的极小一段。我们的未来，也属于这段仍在继续的故事。','Ocean, atmosphere, rock and life shape our home. Homo sapiens emerged about 300,000 years ago: a tiny part of Earth history.','海・大気・岩石・生命が地球を形づくっています。約30万年前に現れた私たちも、この長い物語の一部です。',10,'当代地球','Present day','現在の地球']
];
const words={zh:{brand:'地球与生命',subtitle:'一颗星球，45.4 亿年的故事',sources:'科学来源 ↗',contact:'联系我 ↗',journey:'沿时间轴探索',orbitHint:'拖动地球改变视角 · 双指缩放',previous:'← 上一站',next:'下一站 →',play:'▶ 播放故事',pause:'Ⅱ 暂停故事',speed:'播放速度',today:'回到今天 ↗',natural:'自然',night:'夜幕',blue:'蓝色时刻',rotate:'自转',clouds:'云层',fullscreen:'全屏',zoomIn:'放大',zoomOut:'缩小',timeNote:'Ga = 十亿年前 · Ma = 百万年前 · 事件间距不代表时间比例',detailLabel:'生命的篇章',scienceNote:'远古地表为科学示意，非精确古地理复原；事件年代为约数。',close:'关闭',loading:'正在点亮这颗星球…',ready:'地球已加载',failed:'3D 暂不可用，仍可使用时间轴阅读全部故事。',evidence:'探索科学证据 ↗',modern:'当代地表影像',schematic:'远古地球 · 科学示意'},en:{brand:'Earth & Life',subtitle:'One planet. 4.54 billion years.',sources:'Scientific sources ↗',contact:'Contact ↗',journey:'A journey through time',orbitHint:'Drag to orbit · Pinch to zoom',previous:'← Previous',next:'Next →',play:'▶ Play the story',pause:'Ⅱ Pause the story',speed:'Playback speed',today:'Back to today ↗',natural:'Natural',night:'After dark',blue:'Blue hour',rotate:'Rotation',clouds:'Clouds',fullscreen:'Fullscreen',zoomIn:'Zoom in',zoomOut:'Zoom out',timeNote:'Ga = billion years ago · Ma = million years ago · Event spacing is not linear',detailLabel:'A chapter of life',scienceNote:'Ancient surfaces are schematic, not precise paleogeographic reconstructions. Dates are approximate.',close:'Close',loading:'Bringing our planet into view…',ready:'Earth loaded',failed:'3D is unavailable. All timeline stories are still accessible.',evidence:'Explore the evidence ↗',modern:'Present-day surface imagery',schematic:'Ancient Earth · Schematic'},ja:{brand:'地球と生命',subtitle:'ひとつの惑星、45.4億年の物語',sources:'科学的な出典 ↗',contact:'連絡先 ↗',journey:'時間をたどる旅',orbitHint:'ドラッグで回転 · ピンチで拡大',previous:'← 前へ',next:'次へ →',play:'▶ 物語を再生',pause:'Ⅱ 一時停止',speed:'再生速度',today:'現在へ戻る ↗',natural:'自然',night:'夜',blue:'ブルーアワー',rotate:'自転',clouds:'雲',fullscreen:'全画面',zoomIn:'拡大',zoomOut:'縮小',timeNote:'Ga = 十億年前 · Ma = 百万年前 · イベント間隔は時間に比例しません',detailLabel:'生命の一章',scienceNote:'古代の地表は模式図であり、正確な古地理復元ではありません。年代は概数です。',close:'閉じる',loading:'地球を描いています…',ready:'地球を読み込みました',failed:'3Dを表示できません。時間軸の物語は引き続き閲覧できます。',evidence:'科学的な証拠を読む ↗',modern:'現在の地表画像',schematic:'古代の地球・模式図'}};
const sources=['https://science.nasa.gov/earth/facts/','https://science.nasa.gov/earth/earth-observatory/ancient-crystals-suggest-earlier-ocean/','https://naturalhistory.si.edu/education/teaching-resources/life-science/early-life-earth-animal-origins','https://ocean.si.edu/through-time/ocean-through-time','https://humanorigins.si.edu/evidence/human-fossils/species/homo-sapiens'];
let lang=new URLSearchParams(location.search).get('lang')||'zh';if(!words[lang])lang='zh';
let selected=13, playing=false, speed=1, timer, rotation=true, cloudsOn=true, mode='natural', active=true;
let renderer,scene,camera,planet,clouds,atmosphere,raf=0,ready=false;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const $=id=>document.getElementById(id);
function translateExtras(){
 const copy={zh:['关于这段地球旅程','时间节点参考以下公开资料；远古地球为教学示意。','视觉交互参考','本页独立实现，地表纹理来自 Three.js 示例素材，非实时影像。'],en:['About this journey','Dates and stories follow these public sources. Ancient Earth is an educational schematic.','Visual interaction reference','Independently implemented. Globe textures are from Three.js examples, not live imagery.'],ja:['この地球の旅について','年代と物語は以下の資料を参照。古代の地球は教育用の模式図です。','ビジュアルの参考','独立した実装です。地表画像は Three.js のサンプル素材で、リアルタイム画像ではありません。']}[lang];
 $('sources-title').textContent=copy[0];document.querySelector('.dialog-intro').textContent=copy[1];const credit=document.querySelector('.dialog-credit');credit.replaceChildren(document.createTextNode(copy[2]+' '));const a=document.createElement('a');a.href='https://earth.ethanplus.ai/';a.target='_blank';a.rel='noopener noreferrer';a.textContent='EARTH ↗';credit.append(a,document.createTextNode(' · '+copy[3]));
 document.querySelectorAll('.arrow,.control-icon').forEach(e=>e.hidden=true);
 document.querySelectorAll('button').forEach(b=>{const key=b.querySelector('[data-ui]')?.dataset.ui;if(key&&words[lang][key])b.setAttribute('aria-label',words[lang][key]);});
}
new MutationObserver(translateExtras).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});
function drawLife(i){
  const core=i<2?'M45 50L74 20 100 56 76 91Z':i<5?'M75 24C119 14 139 59 109 88S31 94 30 59 48 31 75 24Z':i<8?'M25 65Q70 15 119 65Q68 110 25 65Z':i<13?'M71 111V48M70 74Q19 75 27 32Q67 30 70 74M72 91Q125 83 116 41Q76 46 72 91':'M72 23A47 47 0 1 0 72 117A47 47 0 1 0 72 23M25 70H119M72 23Q29 70 72 117M72 23Q115 70 72 117';
  $('life-icon').innerHTML=`<svg viewBox="0 0 145 145" aria-hidden="true"><g fill="none" stroke="currentColor" stroke-width="1.3"><circle cx="72" cy="72" r="64" opacity=".12"/><path d="${core}"/><circle cx="72" cy="59" r="7" opacity=".4"/></g></svg>`;
}
function localize(){const t=words[lang];document.documentElement.lang=lang;document.title=t.brand+' — '+t.subtitle;document.querySelectorAll('[data-ui]').forEach(e=>{const v=t[e.dataset.ui];if(v){e.textContent=v;if(e.tagName==='BUTTON')e.setAttribute('aria-label',v);}});$('timeline').setAttribute('aria-label',t.journey);$('timeline-stops').replaceChildren(...records.map((r,i)=>{const b=document.createElement('button');b.type='button';b.innerHTML=`<span>${r[0]}</span><small>${r[lang==='zh'?8:lang==='en'?9:10]}</small>`;b.onclick=()=>select(i,true);return b;}));select(selected);}
function select(i,manual=false){selected=Math.max(0,Math.min(13,i));if(manual)stop();const r=records[selected],li=lang==='zh'?1:lang==='en'?2:3,t=words[lang];$('era-label').textContent=r[li+7];$('era-title').textContent=r[li];$('era-description').textContent=r[li+3];$('era-time').textContent=r[0];$('era-kind').textContent=selected===13?t.modern:t.schematic;$('life-title').textContent=r[li];$('life-description').textContent=r[li+3];$('life-evidence').textContent=t.evidence;$('life-evidence').href=sources[selected===0?0:selected===1?1:selected===13?4:selected<8?2:3];$('timeline').value=selected;$('timeline').setAttribute('aria-valuetext',r[0]+' '+r[li]);$('previous').disabled=selected===0;$('next').disabled=selected===13;$('play').textContent=playing?t.pause:t.play;[...$('timeline-stops').children].forEach((b,n)=>{b.classList.toggle('selected',n===selected);b.setAttribute('aria-current',n===selected?'step':'false');});const b=$('timeline-stops').children[selected];if(b)$('timeline-stops').scrollTo({left:b.offsetLeft-$('timeline-stops').offsetLeft-$('timeline-stops').clientWidth/2+b.clientWidth/2,behavior:reduced?'instant':'smooth'});drawLife(selected);if(planet){planet.material.uniforms.era.value=r[7];planet.material.uniforms.modern.value=selected===13?1:0;clouds.visible=cloudsOn&&selected>0;atmosphere.material.uniforms.tint.value.set(selected===0?'#ee6e31':'#4ca6e8');}reportHeight();}
function stop(){playing=false;clearInterval(timer);$('play').textContent=words[lang].play;$('play').setAttribute('aria-pressed','false');}
function start(){if(selected===13)select(0);playing=true;$('play').textContent=words[lang].pause;$('play').setAttribute('aria-pressed','true');clearInterval(timer);timer=setInterval(()=>{if(selected===13)stop();else select(selected+1);},6500/speed);}
$('play').onclick=()=>playing?stop():start();$('speed').onclick=()=>{speed=speed===1?2:speed===2?.5:1;$('speed').textContent=speed+'×';if(playing)start();};$('previous').onclick=()=>select(selected-1,true);$('next').onclick=()=>select(selected+1,true);$('today').onclick=()=>select(13,true);$('timeline').oninput=e=>select(+e.target.value,true);
$('rotate').onclick=()=>{rotation=!rotation;$('rotate').setAttribute('aria-pressed',String(rotation));};$('clouds').onclick=()=>{cloudsOn=!cloudsOn;$('clouds').setAttribute('aria-pressed',String(cloudsOn));if(clouds)clouds.visible=cloudsOn&&selected>0;};
document.querySelectorAll('.view-mode').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('.view-mode').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));if(planet)planet.material.uniforms.viewMode.value=mode==='night'?1:mode==='blue'?2:0;});
$('sources-open').onclick=()=>$('sources-dialog').showModal();$('sources-close').onclick=()=>$('sources-dialog').close();$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('earth-app').requestFullscreen();}catch{$('loading').hidden=false;$('loading').textContent=lang==='zh'?'此浏览器不支持全屏，请在独立页面打开。':'Fullscreen is unavailable in this browser.';}};
function reportHeight(){if(parent!==window)parent.postMessage({type:'earth-height',height:Math.ceil(document.documentElement.scrollHeight)},location.origin);}
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==parent)return;if(e.data?.type==='earth-language'&&words[e.data.lang]){lang=e.data.lang;localize();}if(e.data?.type==='earth-active'){active=Boolean(e.data.active);if(!active)stop();if(active&&ready&&!raf)animate();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();else if(active&&ready&&!raf)animate();});
new ResizeObserver(reportHeight).observe(document.body);
localize();translateExtras();$('speed').textContent='1×';$('rotate').setAttribute('aria-pressed','true');$('clouds').setAttribute('aria-pressed','true');

const vertex=`varying vec2 vUv;varying vec3 vP;varying vec3 vN;varying vec3 vW;void main(){vUv=uv;vP=position;vW=(modelMatrix*vec4(position,1.)).xyz;vN=normalize(mat3(modelMatrix)*normal);gl_Position=projectionMatrix*viewMatrix*vec4(vW,1.);}`;
const fragment=`precision highp float;uniform sampler2D dayMap;uniform sampler2D nightMap;uniform float era;uniform float modern;uniform float viewMode;varying vec2 vUv;varying vec3 vP;varying vec3 vN;varying vec3 vW;
float hash(vec3 p){return fract(sin(dot(p,vec3(127.1,311.7,74.7)))*43758.5453);}float noise(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(mix(hash(i),hash(i+vec3(1,0,0)),f.x),mix(hash(i+vec3(0,1,0)),hash(i+vec3(1,1,0)),f.x),f.y),mix(mix(hash(i+vec3(0,0,1)),hash(i+vec3(1,0,1)),f.x),mix(hash(i+vec3(0,1,1)),hash(i+vec3(1,1,1)),f.x),f.y),f.z);}float fbm(vec3 p){float a=.5,v=0.;for(int i=0;i<5;i++){v+=a*noise(p);p=p*2.03+2.7;a*=.5;}return v;}
void main(){vec3 p=normalize(vP);float n=fbm(p*4.+vec3(era*.16,0.,era*.1));float fine=fbm(p*55.);float land=smoothstep(.53,.55,n);if(era==6.||era==7.)land=smoothstep(.18,.27,dot(p,normalize(vec3(-.5,.1,1.)))+n*.55);if(era<2.)land=smoothstep(.66,.7,n);vec3 sea=mix(vec3(.015,.06,.11),vec3(.035,.2,.28),fine);vec3 ground=mix(vec3(.22,.2,.12),vec3(.23,.35,.19),fine);if(era<5.)ground=mix(vec3(.25,.21,.17),vec3(.44,.37,.27),fine);vec3 color=mix(sea,ground,land);color+=vec3(.08,.14,.12)*(1.-land)*smoothstep(.515,.535,n)*(1.-smoothstep(.55,.57,n));if(era==0.){float hot=pow(1.-abs(fbm(p*9.)-.5)*2.,22.);color=mix(vec3(.06,.015,.008)*(fine+.3),vec3(1.,.26,.012),hot);color+=vec3(.1,.016,0.)*fine;}if(era==3.)color=mix(vec3(.32,.5,.59),vec3(.85,.92,.9),smoothstep(.27,.57,fine));if(era==7.)color=mix(color,vec3(.3,.13,.045),.45);if(modern>.5)color=texture2D(dayMap,vUv).rgb;
vec3 norm=normalize(vN);vec3 sun=normalize(vec3(-2.5,3.2,4.));float light=dot(norm,sun);float shade=smoothstep(-.16,.85,light);float strength=viewMode==1.?.12:1.;vec3 lit=color*(.11+shade*.95*strength);if(modern>.5){vec3 night=texture2D(nightMap,vUv).rgb;lit+=night*vec3(1.1,.85,.5)*(viewMode==1.?1.:1.-smoothstep(-.12,.22,light));}if(era==0.)lit=color*(.55+.45*shade);if(viewMode==2.)lit=mix(lit,lit*vec3(.5,.9,1.6),.75);vec3 eye=normalize(cameraPosition-vW);float rim=pow(1.-max(dot(eye,norm),0.),3.5);lit+=vec3(.09,.34,.58)*rim*shade*.55;gl_FragColor=vec4(lit,1.);}`;

async function init(){try{
  scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(35,1,.1,100);camera.position.z=4.1;
  renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setClearColor(0x050a0e,0);$('globe').append(renderer.domElement);renderer.domElement.setAttribute('aria-label',words[lang].orbitHint);renderer.domElement.setAttribute('role','img');
  const loader=new THREE.TextureLoader();const [day,night,cloud]=await Promise.all([loader.loadAsync('./assets/earth-day.jpg'),loader.loadAsync('./assets/earth-night.png'),loader.loadAsync('./assets/earth-clouds.png')]);
  const geo=new THREE.SphereGeometry(1,96,64);planet=new THREE.Mesh(geo,new THREE.ShaderMaterial({vertexShader:vertex,fragmentShader:fragment,uniforms:{dayMap:{value:day},nightMap:{value:night},era:{value:10},modern:{value:1},viewMode:{value:0}}}));planet.rotation.y=3.5;planet.rotation.x=.12;scene.add(planet);
  clouds=new THREE.Mesh(geo,new THREE.MeshBasicMaterial({map:cloud,transparent:true,opacity:.22,depthWrite:false,blending:THREE.AdditiveBlending}));clouds.scale.setScalar(1.012);planet.add(clouds);
  atmosphere=new THREE.Mesh(geo,new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.BackSide,blending:THREE.AdditiveBlending,uniforms:{tint:{value:new THREE.Color('#4ca6e8')}},vertexShader:vertex,fragmentShader:'varying vec3 vN;varying vec3 vW;uniform vec3 tint;void main(){float f=pow(max(0.,1.+dot(normalize(vN),normalize(cameraPosition-vW))),4.);gl_FragColor=vec4(tint,f*.32);}'}));atmosphere.scale.setScalar(1.035);scene.add(atmosphere);
  const stars=new THREE.BufferGeometry(),positions=new Float32Array(2100);let seed=918;for(let i=0;i<positions.length;i++){seed=(seed*16807)%2147483647;positions[i]=(seed/2147483647-.5)*50;}stars.setAttribute('position',new THREE.BufferAttribute(positions,3));scene.add(new THREE.Points(stars,new THREE.PointsMaterial({color:0xa8c3d3,size:.027,transparent:true,opacity:.55})));
  const resize=()=>{const r=$('globe').getBoundingClientRect();if(!r.width||!r.height)return;camera.aspect=r.width/r.height;camera.updateProjectionMatrix();renderer.setSize(r.width,r.height);};new ResizeObserver(resize).observe($('globe'));resize();
  const pointers=new Map();let pinch=0;const c=renderer.domElement;c.style.touchAction='none';c.style.cursor='grab';c.addEventListener('pointerdown',e=>{c.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});c.style.cursor='grabbing';});c.addEventListener('pointermove',e=>{const old=pointers.get(e.pointerId);if(!old)return;const dx=e.clientX-old.x,dy=e.clientY-old.y;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){const a=[...pointers.values()];const d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);if(pinch)zoom((pinch-d)*.005);pinch=d;}else{planet.rotation.y+=dx*.005;planet.rotation.x=THREE.MathUtils.clamp(planet.rotation.x+dy*.005,-1.25,1.25);}});const end=e=>{pointers.delete(e.pointerId);pinch=0;c.style.cursor='grab';};c.addEventListener('pointerup',end);c.addEventListener('pointercancel',end);c.addEventListener('lostpointercapture',end);
  c.addEventListener('wheel',e=>{if(e.ctrlKey){e.preventDefault();zoom(e.deltaY*.004);}},{passive:false});$('zoom-in').onclick=()=>zoom(-.3);$('zoom-out').onclick=()=>zoom(.3);
  c.addEventListener('webglcontextlost',e=>{e.preventDefault();ready=false;$('globe').classList.remove('is-ready');$('loading').hidden=false;$('loading').textContent=words[lang].failed;stop();});ready=true;$('globe').classList.add('is-ready');$('loading').textContent=words[lang].ready;$('loading').hidden=true;select(selected);animate();
}catch(e){$('loading').textContent=words[lang].failed;$('globe').classList.add('fallback');console.warn('Earth rendering unavailable',e.message);}}
function zoom(delta){if(camera)camera.position.z=THREE.MathUtils.clamp(camera.position.z+delta,2.6,6.5);}
let last=0;function animate(now=0){raf=0;if(!ready||!active||document.hidden)return;const dt=Math.min((now-last)/1000,.05);last=now;if(rotation&&!reduced)planet.rotation.y+=dt*.018;if(!reduced)clouds.rotation.y+=dt*.005;renderer.render(scene,camera);raf=requestAnimationFrame(animate);}
init();
