export const content = {
  en: {
    brand: 'Lixin Yin',
    nav: {
      about: 'About',
      competitions: 'Competitions',
      awards: 'Awards',
      projects: 'Projects',
      appointments: 'Appointments',
      skills: 'Skills',
      contact: 'Contact',
    },
    hero: {
      name: 'Lixin Yin',
      role: 'Anesthesiologist & Medical AI Researcher',
      institution: "Jiangyin People's Hospital, Jiangsu, China",
      tags: ['Anesthesiology', 'Medical AI', 'Deep Learning', 'Clinical Decision Support', 'Bioinformatics'],
      bio: "I am an anesthesiologist at Jiangyin People's Hospital with a strong interest in applying AI to perioperative medicine and clinical care. My work connects bedside clinical questions with practical AI systems: Kaggle life-science competitions, sleep management, anesthesia safety, medical dataset tooling, and AI-agent workflows for research and care delivery.",
      email: 'Email Me',
      workEmail: 'Work Email',
    },
    competitions: { label: 'International Competitions', title: 'Kaggle Competition Honors' },
    awards: { label: 'National & Regional Recognition', title: 'Awards & Projects' },
    projects: { label: 'Selected GitHub Work', title: 'GitHub Projects', link: 'View Repository', stars: 'stars' },
    appointments: { label: 'Academic Service', title: 'Professional Appointments' },
    skills: { label: 'Technical Expertise', title: 'Key Skills' },
    contact: {
      title: 'Get in Touch',
      desc: 'Interested in collaboration, research discussion, medical AI projects, or practical AI education? Feel free to reach out.',
    },
    footer: "© 2026 Lixin Yin · Jiangyin People's Hospital",
    medals: [
      { icon: '🥈', kind: 'silver', title: 'Stanford RNA 3D Folding', rank: 'Rank 55 / 1,516 teams — Top 3.6%', org: 'Organizer: Stanford University', desc: 'Built high-accuracy deep learning models to predict RNA molecular 3D folding structures, tackling a key computational challenge in life science.', date: 'Sep 2025' },
      { icon: '🥈', kind: 'silver', title: 'CIBMTR — Post-HCT Survival Equity', rank: 'Rank 83 / 3,325 teams — Top 2.5%', org: 'Organizer: CIBMTR', desc: 'Applied AutoML and ensemble methods to build equitable survival prediction models for hematopoietic stem cell transplant patients across diverse populations.', date: 'Mar 2025' },
      { icon: '🥉', kind: 'bronze', title: 'CZII — CryoET Object Identification', rank: 'Rank 51 / 931 teams — Top 5.5%', org: 'Organizer: CZ Imaging Institute', desc: 'Developed a high-recall 3D object detection model to identify protein complexes in cryo-electron tomography data.', date: 'Feb 2025' },
    ],
    awardsList: [
      { badge: '3rd Prize', title: '2025 Inaugural "AI Navigation Cup" — AI+ Skills Contest', project: 'AnesGuardian — Intelligent Anesthesia Guardian System', meta: 'Organizer: Internet Society of China · Track: AI + Medical Health · Nov 2025', desc: 'Participated in developing a perioperative intelligent monitoring and early-warning system to enhance anesthesia safety.' },
      { badge: 'Top 8 · Best Practice', title: '2025 Digital China Innovation Contest', project: 'AI-Powered Full-Cycle Sleep Management Platform', meta: 'Organizer: 8th Digital China Summit · Track: Artificial Intelligence · Apr 2025', desc: 'Led the algorithm design for a full-cycle sleep intervention and management system; recognized for practical application value.' },
      { badge: 'Outstanding Case', title: '2025 Data Content Annual Case Collection', project: 'Smart-Fit-Agent', meta: 'Organizer: Fudan University & The Paper · Feb 2025', desc: 'Designed and developed an AI-driven personalized health adaptation agent and explored LLM-agent applications in health management.' },
      { badge: '3rd Prize', title: '2025 Jiangsu Province "Data Factor ×" Jiangyin Regional Competition', project: 'Medical Health Data Factor Development & Utilization', meta: 'Organizer: Jiangyin Data Bureau & Jiangyin Federation of Trade Unions · Oct 2025', desc: 'Explored practical use of healthcare data elements in regional digital-health scenarios.' },
      { badge: '3rd Prize', title: '2025 National Smart Medical Insurance Competition', project: 'Medical Insurance Value Compass (Agent Edition)', meta: "Organizer: National Healthcare Security Administration · Team: Datapower · Jiangyin People's Hospital", desc: 'Built an agent-style view of medical-insurance value assessment for healthcare decision support.' },
    ],
    projectsList: [
      { name: 'MedicalAI-Platform', stars: 48, url: 'https://github.com/2023Anita/MedicalAI-Platform', desc: 'A multi-agent medical analysis platform for structured health-report interpretation and clinical reasoning workflows.', tags: ['TypeScript', 'Medical AI', 'Agents'] },
      { name: 'Smart-Fit-Agent', stars: 10, url: 'https://github.com/2023Anita/Smart-Fit-Agent', desc: 'An AI-powered health management app for personalized meal plans, exercise routines, and food analysis.', tags: ['TypeScript', 'Health Agent', 'Lifestyle'] },
      { name: 'med-dataset-platform', stars: 3, url: 'https://github.com/2023Anita/med-dataset-platform', desc: 'A professional platform for generating, managing, and exporting medical AI datasets.', tags: ['JavaScript', 'Dataset', 'Medical AI'] },
      { name: 'AnesGuardian', stars: 0, url: 'https://github.com/2023Anita/AnesGuardian', desc: 'A perioperative anesthesia assessment and decision-support platform focused on anesthesia safety.', tags: ['TypeScript', 'Anesthesia', 'CDSS'] },
      { name: 'emergency-mdt-ai-platform', stars: 0, url: 'https://github.com/2023Anita/emergency-mdt-ai-platform', desc: 'An emergency MDT decision-support platform for triage, differential diagnosis, OCR report parsing, and patient workflow design.', tags: ['TypeScript', 'Emergency', 'Workflow'] },
      { name: 'openai-agents-medical-research-guide', stars: 0, url: 'https://github.com/2023Anita/openai-agents-medical-research-guide', desc: 'A multilingual OpenAI Agents SDK course built around a safety-first medical research assistant.', tags: ['MDX', 'Course', 'OpenAI Agents'] },
      { name: 'agent-token-budget', stars: 3, url: 'https://github.com/2023Anita/agent-token-budget', desc: 'A visual, copy-ready guide for AI coding agent token budgets and safety boundaries.', tags: ['CSS', 'AI Coding', 'Guide'] },
      { name: 'ai-coding-intel-radar', stars: 2, url: 'https://github.com/2023Anita/ai-coding-intel-radar', desc: 'A Cloudflare + Codex + Obsidian template for a daily AI coding intelligence radar.', tags: ['JavaScript', 'Cloudflare', 'Obsidian'] },
      { name: 'codex-video-director-skill', stars: 0, url: 'https://github.com/2023Anita/codex-video-director-skill', desc: 'A storyboard-driven Codex skill for AI video production and dual-style demos.', tags: ['JavaScript', 'Video', 'Skill'] },
      { name: 'idea-evaluator', stars: 0, url: 'https://github.com/2023Anita/idea-evaluator', desc: 'A skill-orchestration and idea-evaluation toolkit for AI developers.', tags: ['Shell', 'AI Tools', 'Skills'] },
    ],
    appointmentsList: [
      { icon: 'shield', role: 'Expert Reviewer', org: 'Fuzhou Municipal Health Science & Technology Program Expert Panel', date: 'Enrolled Oct 2025 · Specialties: Anesthesiology, Clinical Decision Support' },
      { icon: 'book', role: 'Peer Reviewer', org: 'Chinese Medical Association — Digital Medicine and Health Journal', date: 'Enrolled Jun 2024 · Specialty: Medicine × AI Interdisciplinary' },
    ],
    skillsList: [
      { cat: 'Clinical Medicine', items: ['Clinical anesthesia management', 'Perioperative medicine', 'Physiological parameter monitoring'] },
      { cat: 'Deep Learning', items: ['PyTorch / TensorFlow', 'Transformer architectures', 'CNN, ResNet variants'] },
      { cat: 'Computer Vision', items: ['3D medical image processing', 'CryoET / CT / MRI analysis', '3D object detection'] },
      { cat: 'Bioinformatics', items: ['RNA / protein structure prediction', 'AlphaFold-related methods', 'Molecular property modeling'] },
      { cat: 'Structured Data Analysis', items: ['Survival analysis', 'AutoML / ensemble methods', 'Clinical outcome modeling'] },
      { cat: 'AI Agents & LLMs', items: ['LLM-based agent design', 'Health management applications', 'Clinical AI deployment'] },
    ],
  },
  zh: {
    brand: '殷利鑫',
    nav: { about: '关于', competitions: '竞赛', awards: '奖项', projects: '项目', appointments: '任职', skills: '技能', contact: '联系' },
    hero: {
      name: '殷利鑫',
      role: '麻醉医生 / 医疗人工智能实践者',
      institution: '江阴市人民医院，江苏，中国',
      tags: ['麻醉学', '医疗 AI', '深度学习', '临床决策支持', '生物信息学'],
      bio: '我是江阴市人民医院麻醉科医生，长期关注人工智能在围术期医学、临床照护和医学科研中的实际应用。我的工作重点是把一线临床问题转化为可计算、可验证、可复盘的 AI 系统，包括 Kaggle 生命科学竞赛、睡眠管理、麻醉安全、医疗数据集工具和 AI Agent 科研工作流。',
      email: '给我发邮件',
      workEmail: '工作邮箱',
    },
    competitions: { label: '国际竞赛', title: 'Kaggle 竞赛荣誉' },
    awards: { label: '国家与区域成果', title: '奖项与项目' },
    projects: { label: '精选 GitHub 作品', title: 'GitHub 代表项目', link: '查看仓库', stars: 'stars' },
    appointments: { label: '学术服务', title: '专业任职' },
    skills: { label: '技术能力', title: '核心技能' },
    contact: { title: '联系我', desc: '如果你对医学人工智能、科研协作、临床 AI 项目或 AI 教学感兴趣，欢迎联系。' },
    footer: '© 2026 殷利鑫 · 江阴市人民医院',
    medals: [
      { icon: '🥈', kind: 'silver', title: 'Stanford RNA 3D Folding', rank: '第 55 / 1,516 队 — Top 3.6%', org: '主办方：斯坦福大学', desc: '构建高精度深度学习模型预测 RNA 分子三维折叠结构，解决生命科学中的关键计算问题。', date: '2025 年 9 月' },
      { icon: '🥈', kind: 'silver', title: 'CIBMTR — Post-HCT Survival Equity', rank: '第 83 / 3,325 队 — Top 2.5%', org: '主办方：CIBMTR', desc: '结合 AutoML 与集成学习，构建造血干细胞移植后患者生存率公平性预测模型。', date: '2025 年 3 月' },
      { icon: '🥉', kind: 'bronze', title: 'CZII — CryoET Object Identification', rank: '第 51 / 931 队 — Top 5.5%', org: '主办方：CZ Imaging Institute', desc: '开发高召回率 3D 目标检测模型，在冷冻电子断层扫描数据中识别细胞内蛋白复合物。', date: '2025 年 2 月' },
    ],
    awardsList: [
      { badge: '三等奖', title: '2025 首届“AI 领航杯”人工智能+应用与技能大赛', project: 'AnesGuardian - 智能麻醉守护神', meta: '主办方：中国互联网协会 · AI+医疗健康赛道 · 2025 年 11 月', desc: '参与开发围术期智能监测与预警系统，面向麻醉安全场景提升风险识别能力。' },
      { badge: '第八名 · 最具实践应用奖', title: '2025 中国数字创新大赛', project: 'AI 智助入梦，精准守护深眠 - 全周期睡眠管理平台', meta: '主办方：第八届数字中国建设峰会组委会 · 人工智能赛道 · 2025 年 4 月', desc: '主导睡眠干预与管理系统的算法逻辑设计，项目获得实践应用价值认可。' },
      { badge: 'AI 应用杰出案例', title: '2025 数据内容年度案例征集', project: 'Smart-Fit-Agent', meta: '主办方：复旦大学与澎湃新闻 · 2025 年 2 月', desc: '设计并开发个性化健康适应代理，探索大模型 Agent 在个人健康管理中的应用路径。' },
      { badge: '三等奖', title: '2025 年江苏省“数据要素×”江阴区域赛', project: '医疗健康数据要素开发与利用', meta: '主办方：江阴市数据局、江阴市总工会 · 2025 年 10 月', desc: '围绕区域数字健康场景，探索医疗数据要素的实际开发利用。' },
      { badge: '三等奖', title: '2025 全国智慧医保大赛', project: '医保价值罗盘（Agent 版）', meta: '主办方：国家医疗保障局 · Datapower 团队 · 江阴市人民医院', desc: '以智能体方式呈现医保价值评估视角，服务医疗决策支持。' },
    ],
    projectsList: [
      { name: 'MedicalAI-Platform', stars: 48, url: 'https://github.com/2023Anita/MedicalAI-Platform', desc: '多智能体医疗分析平台，面向体检报告结构化解读和临床推理工作流。', tags: ['TypeScript', '医疗 AI', 'Agents'] },
      { name: 'Smart-Fit-Agent', stars: 10, url: 'https://github.com/2023Anita/Smart-Fit-Agent', desc: '个性化健康管理应用，支持饮食计划、运动方案和食物智能分析。', tags: ['TypeScript', '健康 Agent', '生活方式'] },
      { name: 'med-dataset-platform', stars: 3, url: 'https://github.com/2023Anita/med-dataset-platform', desc: '专业医疗 AI 数据集生成、管理与导出平台。', tags: ['JavaScript', '数据集', '医疗 AI'] },
      { name: 'AnesGuardian', stars: 0, url: 'https://github.com/2023Anita/AnesGuardian', desc: '围术期麻醉评估与决策支持平台，聚焦麻醉安全。', tags: ['TypeScript', '麻醉', '临床决策'] },
      { name: 'emergency-mdt-ai-platform', stars: 0, url: 'https://github.com/2023Anita/emergency-mdt-ai-platform', desc: '急诊 MDT 决策支持平台，覆盖分诊、鉴别诊断、报告 OCR 和患者流程设计。', tags: ['TypeScript', '急诊', '工作流'] },
      { name: 'openai-agents-medical-research-guide', stars: 0, url: 'https://github.com/2023Anita/openai-agents-medical-research-guide', desc: '围绕安全医学科研助手构建的 OpenAI Agents SDK 多语言课程。', tags: ['MDX', '课程', 'OpenAI Agents'] },
      { name: 'agent-token-budget', stars: 3, url: 'https://github.com/2023Anita/agent-token-budget', desc: '面向 AI 编程智能体的 token 预算与安全边界可视化指南。', tags: ['CSS', 'AI Coding', '指南'] },
      { name: 'ai-coding-intel-radar', stars: 2, url: 'https://github.com/2023Anita/ai-coding-intel-radar', desc: 'Cloudflare + Codex + Obsidian 的每日 AI 编程情报雷达模板。', tags: ['JavaScript', 'Cloudflare', 'Obsidian'] },
      { name: 'codex-video-director-skill', stars: 0, url: 'https://github.com/2023Anita/codex-video-director-skill', desc: '基于 storyboard 的 AI 视频生产 Codex skill 与双风格演示。', tags: ['JavaScript', '视频', 'Skill'] },
      { name: 'idea-evaluator', stars: 0, url: 'https://github.com/2023Anita/idea-evaluator', desc: '面向 AI 开发者的 skill 编排与想法评估工具。', tags: ['Shell', 'AI 工具', 'Skills'] },
    ],
    appointmentsList: [
      { icon: 'shield', role: '评审专家', org: '福州市卫生健康科技计划项目专家库', date: '2025 年 10 月入库 · 专业方向：麻醉学、临床决策支持' },
      { icon: 'book', role: '审稿专家', org: '中华医学会《数字医学与健康》期刊', date: '2024 年 6 月入库 · 医学与人工智能交叉方向' },
    ],
    skillsList: [
      { cat: '临床医学', items: ['临床麻醉管理', '围术期医学', '生理参数监测与分析'] },
      { cat: '深度学习', items: ['PyTorch / TensorFlow', 'Transformer 架构', 'CNN 与 ResNet 变体'] },
      { cat: '计算机视觉', items: ['3D 医学影像处理', 'CryoET / CT / MRI 分析', '三维目标检测'] },
      { cat: '生物信息学', items: ['RNA / 蛋白结构预测', 'AlphaFold 相关方法', '分子性质建模'] },
      { cat: '结构化数据分析', items: ['生存分析', 'AutoML / 集成学习', '临床结局建模'] },
      { cat: 'AI Agents 与大模型', items: ['LLM Agent 设计', '健康管理应用', '临床 AI 部署'] },
    ],
  },
  ja: {
    brand: '殷 利鑫',
    nav: { about: '概要', competitions: 'コンペ', awards: '受賞', projects: 'プロジェクト', appointments: '専門活動', skills: 'スキル', contact: '連絡先' },
    hero: {
      name: '殷 利鑫',
      role: '麻酔科医 / 医療 AI 実践者',
      institution: '江陰市人民医院（中国・江蘇省）',
      tags: ['麻酔学', '医療 AI', '深層学習', '臨床意思決定支援', 'バイオインフォマティクス'],
      bio: '江陰市人民医院の麻酔科医として、周術期医療、臨床ケア、医学研究における AI 活用に取り組んでいます。臨床現場の課題を、計算可能で検証可能な AI システムへ落とし込むことを重視し、Kaggle の生命科学コンペ、睡眠管理、麻酔安全、医療データセット基盤、AI Agent による研究ワークフローを実践しています。',
      email: 'メールする',
      workEmail: '勤務先メール',
    },
    competitions: { label: '国際コンペティション', title: 'Kaggle 受賞歴' },
    awards: { label: '国内・地域での評価', title: '受賞とプロジェクト' },
    projects: { label: 'GitHub 代表作', title: 'GitHub 代表プロジェクト', link: 'リポジトリを見る', stars: 'stars' },
    appointments: { label: '学術サービス', title: '専門活動' },
    skills: { label: '技術領域', title: '主要スキル' },
    contact: { title: 'お問い合わせ', desc: '医療 AI、研究協力、臨床 AI プロジェクト、実践的な AI 教育に関心がありましたら、お気軽にご連絡ください。' },
    footer: '© 2026 殷 利鑫 · 江陰市人民医院',
    medals: [
      { icon: '🥈', kind: 'silver', title: 'Stanford RNA 3D Folding', rank: '55 位 / 1,516 チーム — Top 3.6%', org: '主催：Stanford University', desc: 'RNA 分子の三次元折りたたみ構造を予測する高精度な深層学習モデルを構築し、生命科学上の重要な計算課題に取り組みました。', date: '2025 年 9 月' },
      { icon: '🥈', kind: 'silver', title: 'CIBMTR — Post-HCT Survival Equity', rank: '83 位 / 3,325 チーム — Top 2.5%', org: '主催：CIBMTR', desc: 'AutoML とアンサンブル手法を用いて、造血幹細胞移植後の生存予測における公平性を重視したモデルを構築しました。', date: '2025 年 3 月' },
      { icon: '🥉', kind: 'bronze', title: 'CZII — CryoET Object Identification', rank: '51 位 / 931 チーム — Top 5.5%', org: '主催：CZ Imaging Institute', desc: 'クライオ電子線トモグラフィー画像から細胞内タンパク質複合体を検出する、高再現率の 3D 物体検出モデルを開発しました。', date: '2025 年 2 月' },
    ],
    awardsList: [
      { badge: '三等賞', title: '2025 第1回「AI Navigation Cup」AI+ 応用・技能コンテスト', project: 'AnesGuardian - Intelligent Anesthesia Guardian System', meta: '主催：中国インターネット協会 · AI+医療健康部門 · 2025 年 11 月', desc: '周術期のモニタリングと早期警告を支援するシステム開発に参加し、麻酔安全の向上を目指しました。' },
      { badge: 'Top 8 · Best Practice', title: '2025 Digital China Innovation Contest', project: 'AI による全周期睡眠管理プラットフォーム', meta: '主催：第8回 Digital China Summit 組織委員会 · AI 部門 · 2025 年 4 月', desc: '睡眠介入・管理システムのアルゴリズム設計を主導し、実践応用価値が評価されました。' },
      { badge: '優秀事例', title: '2025 Data Content Annual Case Collection', project: 'Smart-Fit-Agent', meta: '主催：復旦大学・澎湃新聞 · 2025 年 2 月', desc: '個別化された健康適応エージェントを設計・開発し、大規模言語モデル Agent の健康管理応用を探りました。' },
      { badge: '三等賞', title: '2025 江蘇省「Data Factor ×」江陰地域コンペティション', project: '医療健康データ要素の開発と活用', meta: '主催：江陰市データ局・江陰市総工会 · 2025 年 10 月', desc: '地域デジタルヘルスの文脈で、医療データ要素の実践的な活用を検討しました。' },
      { badge: '三等賞', title: '2025 全国スマート医療保険コンテスト', project: 'Medical Insurance Value Compass（Agent 版）', meta: '主催：国家医療保障局 · Team Datapower · 江陰市人民医院', desc: '医療保険価値評価を Agent 形式で整理し、医療意思決定支援に活用する視点を示しました。' },
    ],
    projectsList: [
      { name: 'MedicalAI-Platform', stars: 48, url: 'https://github.com/2023Anita/MedicalAI-Platform', desc: '健診レポートの構造化解釈と臨床推論ワークフローを支援する、マルチエージェント医療分析プラットフォーム。', tags: ['TypeScript', '医療 AI', 'Agents'] },
      { name: 'Smart-Fit-Agent', stars: 10, url: 'https://github.com/2023Anita/Smart-Fit-Agent', desc: '食事計画、運動プラン、食品分析を支援する個別化健康管理アプリ。', tags: ['TypeScript', '健康 Agent', '生活習慣'] },
      { name: 'med-dataset-platform', stars: 3, url: 'https://github.com/2023Anita/med-dataset-platform', desc: '医療 AI データセットの生成、管理、エクスポートを行う専門プラットフォーム。', tags: ['JavaScript', 'データセット', '医療 AI'] },
      { name: 'AnesGuardian', stars: 0, url: 'https://github.com/2023Anita/AnesGuardian', desc: '麻酔安全を重視した、周術期麻酔評価・意思決定支援プラットフォーム。', tags: ['TypeScript', '麻酔', 'CDSS'] },
      { name: 'emergency-mdt-ai-platform', stars: 0, url: 'https://github.com/2023Anita/emergency-mdt-ai-platform', desc: 'トリアージ、鑑別診断、OCR レポート解析、患者ワークフロー設計を支援する救急 MDT プラットフォーム。', tags: ['TypeScript', '救急', 'ワークフロー'] },
      { name: 'openai-agents-medical-research-guide', stars: 0, url: 'https://github.com/2023Anita/openai-agents-medical-research-guide', desc: '安全性を重視した医学研究アシスタントを題材にした、OpenAI Agents SDK の多言語コース。', tags: ['MDX', 'コース', 'OpenAI Agents'] },
      { name: 'agent-token-budget', stars: 3, url: 'https://github.com/2023Anita/agent-token-budget', desc: 'AI コーディングエージェントの token 予算と安全境界を可視化した実用ガイド。', tags: ['CSS', 'AI Coding', 'ガイド'] },
      { name: 'ai-coding-intel-radar', stars: 2, url: 'https://github.com/2023Anita/ai-coding-intel-radar', desc: 'Cloudflare、Codex、Obsidian を組み合わせた日次 AI コーディング情報レーダーのテンプレート。', tags: ['JavaScript', 'Cloudflare', 'Obsidian'] },
      { name: 'codex-video-director-skill', stars: 0, url: 'https://github.com/2023Anita/codex-video-director-skill', desc: 'ストーリーボード駆動の AI 動画制作を支援する Codex skill とデモ。', tags: ['JavaScript', '動画', 'Skill'] },
      { name: 'idea-evaluator', stars: 0, url: 'https://github.com/2023Anita/idea-evaluator', desc: 'AI 開発者向けの skill オーケストレーションとアイデア評価ツール。', tags: ['Shell', 'AI ツール', 'Skills'] },
    ],
    appointmentsList: [
      { icon: 'shield', role: '評価専門家', org: '福州市衛生健康科学技術計画プロジェクト専門家パネル', date: '2025 年 10 月登録 · 専門：麻酔学、臨床意思決定支援' },
      { icon: 'book', role: '査読者', org: '中華医学会「Digital Medicine and Health」誌', date: '2024 年 6 月登録 · 医学と AI の学際領域' },
    ],
    skillsList: [
      { cat: '臨床医学', items: ['臨床麻酔管理', '周術期医学', '生理パラメータの監視と分析'] },
      { cat: '深層学習', items: ['PyTorch / TensorFlow', 'Transformer アーキテクチャ', 'CNN と ResNet 系モデル'] },
      { cat: 'コンピュータビジョン', items: ['3D 医用画像処理', 'CryoET / CT / MRI 解析', '3D 物体検出'] },
      { cat: 'バイオインフォマティクス', items: ['RNA / タンパク質構造予測', 'AlphaFold 関連手法', '分子特性モデリング'] },
      { cat: '構造化データ分析', items: ['生存分析', 'AutoML / アンサンブル手法', '臨床アウトカムモデリング'] },
      { cat: 'AI Agents と LLM', items: ['LLM ベースの Agent 設計', '健康管理アプリケーション', '臨床 AI の実装'] },
    ],
  },
};
